[project]
name = "mp3-transcriber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy==1.26.3",
    "openai-whisper==20231117",
    "pyqt5==5.15.9",
    "python-docx==1.0.1",
    "torch==2.2.0",
]
